### ISSUE TITLE
Issue with Flashlight loop, Seems to be running at all times even whilst weapon is put away

### ISSUE THREAD

**Issue by JordanByrne556** [DistinctiveDevelopment/DD-PERSISTENTFLASHLIGHT#1]
This is causing the Click noise to be heard at all and any times whilst pressing E I found this issue whilst developing another script in C# And Putting them both together hope my input helps, Here is an example video
https://www.mediafire.com/file/75krj5b6sgjbh6d/2022-02-11_21-23-38.mkv/file

**Comment by Oulsen** [comment]
8899e2e6bd52439d8e6fc33abd4aa4e998c39075 -  Fixed click sound being played while not holding any weapons and pressing E
